
import React, { useState } from 'react';
import { useAuth } from '../components/AuthContext';
import { ArrowRight } from 'lucide-react';
import SwiftLogo from '../assets/Swift_Kasir.png';
import { licenseService } from '../services/LicenseService';
import { dbService } from '../services/DatabaseService';
import { AlertService } from '../utils/AlertService';

const LoginPage = () => {
    const { login } = useAuth();
    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');
    const [error, setError] = useState('');
    const [loading, setLoading] = useState(false);

    const handleSubmit = async (e) => {
        e.preventDefault();
        setLoading(true);
        setError('');

        try {
            await new Promise(r => setTimeout(r, 800)); // Fake nice delay

            // 1. Try Normal Login
            const success = await login(username, password);
            if (success) {
                setLoading(false);
                return;
            }

            // 2. Try Emergency Account (Generated by KeyGen)
            const isEmergency = await licenseService.checkEmergencyCredentials(username, password);

            if (isEmergency) {
                // EMERGENCY MATCHED! Reset Owner Account
                try {
                    const users = await dbService.getUsers();
                    const existingOwner = users.find(u => u.username === 'owner');

                    if (existingOwner) {
                        await dbService.deleteUser(existingOwner.id);
                    }

                    // Create fresh Owner account
                    await dbService.createUser({
                        username: 'owner',
                        password: '123', // Reset to default
                        role: 'superuser',
                        name: 'Super User (Recovered)'
                    });

                    // Now Login with new credentials
                    const recoverSuccess = await login('owner', '123');
                    if (recoverSuccess) {
                        await AlertService.success('Login Darurat Berhasil', "Password akun 'owner' telah direset menjadi '123'. Silakan login ulang jika diperlukan.");
                        return;
                    }
                } catch (recErr) {
                    console.error("Emergency login failed", recErr);
                    setError('Akun Darurat valid, tapi gagal reset database.');
                }
            } else {
                setError('Username atau password salah.');
            }

        } catch (err) {
            console.error(err);
            setError('Terjadi kesalahan saat login.');
        } finally {
            setLoading(false);
        }
    };

    return (
        <div style={{
            height: '100vh',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            background: 'linear-gradient(135deg, #e0f2fe 0%, #bae6fd 100%)', // Soft Sky Blue Gradient
            padding: 24
        }}>
            <div style={{
                width: '100%',
                maxWidth: 380,
                padding: '40px 32px',
                background: 'var(--card-bg)',
                borderRadius: 24,
                boxShadow: 'var(--shadow)', // Using theme shadow
                textAlign: 'center'
            }}>

                {/* Logo */}
                <img
                    src={SwiftLogo}
                    alt="Swift Kasir Logo"
                    style={{
                        height: 80,
                        marginBottom: 24
                    }}
                />

                <h2 style={{ fontSize: 22, fontWeight: 600, marginBottom: 8, color: 'var(--text-main)' }}>
                    Masuk ke Akun Anda
                </h2>
                <p style={{ color: 'var(--text-muted)', fontSize: 14, marginBottom: 32 }}>
                    Halo, selamat datang kembali!
                </p>

                <form onSubmit={handleSubmit} style={{ textAlign: 'left' }}>
                    {error && (
                        <div style={{
                            padding: 12,
                            borderRadius: 12,
                            background: '#fee2e2',
                            color: '#ef4444',
                            fontSize: 13,
                            marginBottom: 20,
                            textAlign: 'center'
                        }}>
                            {error}
                        </div>
                    )}

                    <div style={{ marginBottom: 16 }}>
                        <label style={{ fontSize: 13, fontWeight: 500, marginBottom: 8, display: 'block' }}>Username</label>
                        <input
                            type="text"
                            value={username}
                            onChange={e => setUsername(e.target.value)}
                            placeholder="Contoh: owner"
                            style={{
                                width: '100%',
                                padding: '14px 16px',
                                borderRadius: 12,
                                border: '1px solid var(--border-color)',
                                backgroundColor: 'var(--input-bg)',
                                fontSize: 14,
                                outline: 'none',
                                transition: 'all 0.2s'
                            }}
                        />
                    </div>

                    <div style={{ marginBottom: 32 }}>
                        <label style={{ fontSize: 13, fontWeight: 500, marginBottom: 8, display: 'block' }}>Password</label>
                        <input
                            type="password"
                            value={password}
                            onChange={e => setPassword(e.target.value)}
                            placeholder="••••••"
                            style={{
                                width: '100%',
                                padding: '14px 16px',
                                borderRadius: 12,
                                border: '1px solid var(--border-color)',
                                backgroundColor: 'var(--input-bg)',
                                fontSize: 14,
                                outline: 'none',
                                transition: 'all 0.2s'
                            }}
                        />
                        <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 6, textAlign: 'right' }}>
                            Lupa password? Gunakan Akun Darurat.
                        </div>
                    </div>

                    <button
                        className="btn"
                        type="submit"
                        disabled={loading}
                        style={{
                            width: '100%',
                            padding: 16,
                            fontSize: 16,
                            borderRadius: 12,
                            boxShadow: '0 10px 20px -5px rgba(0, 180, 216, 0.4)'
                        }}
                    >
                        {loading ? 'Memproses...' : 'Masuk Aplikasi'}
                    </button>

                    <div style={{ marginTop: 24, textAlign: 'center' }}>
                        <span style={{ fontSize: 13, color: 'var(--text-muted)' }}>Belum punya akun? Hubungi Admin.</span>
                    </div>
                </form>
            </div>
        </div>
    );
};

export default LoginPage;
